controller_list:
  - name: fake_panda_arm_controller
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
  - name: fake_hithand_controller
    joints:
      - Right_Index_1
      - Right_Index_2
      - Right_Index_3
      - Right_Index_4
      - Right_Little_1
      - Right_Little_2
      - Right_Little_3
      - Right_Little_4
      - Right_Middle_1
      - Right_Middle_2
      - Right_Middle_3
      - Right_Middle_4
      - Right_Ring_1
      - Right_Ring_2
      - Right_Ring_3
      - Right_Ring_4
      - Right_Thumb_1
      - Right_Thumb_2
      - Right_Thumb_3
      - Right_Thumb_4
initial:  # Define initial robot poses.
#  - group: panda_arm
#    pose: home
